openapi: '3.1.1'
info:
  title: Quotation API
  version: '1.0.0'
servers:
  - url: https://api.predic8.de/

paths:
  /rfqs:
    post:
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - product
              properties:
                id:
                  type: string
                price:
                  type: number
                shipment:
                  type: string
                product:
                  type: char

      responses:
        '200':
          description: OK