openapi: '3.0.2'
info:
  title: Quotation API
  version: '1.0'
  contact:
    email: bayer@predic8.de
  description: The API for Quotations
servers:
  - url: https://api.server.test/v1

paths:
  /rfqs:
    post:
      operationId: requestQuote
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Quotation"

      responses:
        '200':
          description: OK
        '201':
          description: OK

components:
  schemas:
    Quotation:
      type: object
      required:
        - id
      properties:
        id:
          type: string
          format: uuid
        product:
          type: string
          maxLength: 20
          pattern: '(\w+\W*)*'
        quantity:
          type: number
          # format: int32
          minimum: 0
          maximum: 500
        price:
          type: number
          minimum: 0
        shipment:
          type: string
          enum:
            - FOB
            - DAT
        mode:
          type: string
          pattern: "[A-Z]{3}"
          maxLength: 3