name: OpenAPI Checks

on:
  - pull_request

env:
  RULES_VERSION: v4

jobs:
  OAS-Rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g @stoplight/spectral-cli
      - run: spectral lint -r https://raw.githubusercontent.com/predic8/openapi-rules/$RULES_VERSION/spectral-oas.yml rfq-api-v1.oas.yml
  Security-Rules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g @stoplight/spectral-cli
      - run: spectral lint -r https://raw.githubusercontent.com/predic8/openapi-rules/$RULES_VERSION/spectral-security.yml rfq-api-v1.oas.yml