name: OpenAPI Checks

on:
  - pull_request

env:
  RULES_VERSION: v7

jobs:
  "Lint OAS":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g @stoplight/spectral-cli
      - run: wget https://raw.githubusercontent.com/predic8/openapi-rules/$RULES_VERSION/spectral-oas.yml -O .spectral.yml
      - run: spectral lint rfq-api-v1.oas.yml

  "Lint OWASP":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g @stoplight/spectral-cli
      - run: npm install --save -D @stoplight/spectral-owasp-ruleset
      - run: wget https://raw.githubusercontent.com/predic8/openapi-rules/$RULES_VERSION/spectral-security.yml -O .spectral.yml
      - run: spectral lint rfq-api-v1.oas.yml

  "Lint Styleguide":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g @stoplight/spectral-cli
      - run: wget https://raw.githubusercontent.com/predic8/openapi-rules/$RULES_VERSION/spectral-security.yml  --verbose  -O .spectral.yml
      - run: spectral lint rfq-api-v1.oas.yml

  "Check Compatibility":
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.3'
      - run: go install github.com/tufin/oasdiff@latest
      - name: Check version compatibility
        run: oasdiff -fail-on-diff -base rfq-api-v1-ref.oas.yml -revision rfq-api-v1.oas.yml

