name: Check Compatibility

on:
  - pull_request

jobs:
  Compatibility:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.3'
      - run: go install github.com/tufin/oasdiff@latest
      - run: |
          oasdiff breaking -o ERR \
            https://github.com/andymaier/rfq-api/releases/download/v1.2.0/rfq-api-v1.oas.yml rfq-api-v1.oas.yml