name: Release OpenAPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  GH_TOKEN: ${{ github.token }}
  API_LIFECYCLE_SECRET: ${{ secrets.ApiLifecycleTrigger }}

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Release "${{ github.ref_name }}"
        run: gh release create --generate-notes "${{ github.ref_name }}" "rfq-api-v1.oas.yml#OpenAPI"
      - name: Trigger API-Gateway Deployment
        run: |
          export GH_TOKEN=$API_LIFECYCLE_SECRET
          gh workflow run actions.yml -R "predic8/api-lifecycle-gateway"