name: Release OpenAPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  GH_TOKEN: ${{ github.token }}

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: gh release create --generate-notes "${{ github.ref_name }}" "rfq-api-v1.oas.yml#OpenAPI"
      - run: gh auth login --with-token $TRIGGER_GW_TOKEN
      - run: gh workflow run actions.yml -R "predic8/api-lifecycle-gateway"
          
#  - run: gh release create --generate-notes -t "${{ github.ref_name }}" "${{ github.ref_name }}" "rfq-api-v1.oas.yml#OpenAPI"