name: Release OpenAPI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  API_LIFECYCLE_SECRET: ${{ secrets.ApiLifecycleTrigger }}

jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: gh release create --generate-notes "${{ github.ref_name }}" "rfq-api-v1.oas.yml#OpenAPI"
      - run: |
          export GH_TOKEN=$API_LIFECYCLE_SECRET
          gh workflow run actions.yml -R "andymaier/api-lifecycle-gateway"